# Generated by Django 4.0.10 on 2024-04-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('attention_image', models.ImageField(blank=True, null=True, upload_to='attention_images/')),
            ],
        ),
    ]
