# Generated by Django 4.0.10 on 2024-04-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_generator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='attention_image',
            field=models.ImageField(blank=True, null=True, upload_to='image_caption_generator_model/attention_images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='image_caption_generator_model/uploaded_images/'),
        ),
    ]
