# Generated by Django 4.0.10 on 2024-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_generator_app', '0002_alter_uploadedimage_attention_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='attention_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images_with_attention/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploaded_images/'),
        ),
    ]
